### ISSUE TITLE
登录验证无效

### ISSUE THREAD

**Issue by mark4z** [Laverrr/bookstore#1]
点击登录无反应(when the first time)

**Comment by Laverrr** [comment]
> 点击登录无反应
It will happen when the first time click login button. I still working on it , I have been busy these days.When I fix it, I will inform u，or u can find it out by yourself. LOL~

**Comment by Laverrr** [comment]
> > 点击登录无反应
> > It will happen when the first time click login button. I still working on it , I have been busy these days.When I fix it, I will inform u，or u can find it out by yourself. LOL~

fixed,the issue is ajax fail in the first time and I found the answer in stack  overflow.
I changed the type of login button from "submit" to "button".
the problom is  when click the button of "submit" the page will reload without waiting the data from backend.
Here is the original  https://stackoverflow.com/questions/11416941/ajax-not-working-first-time?rq=1
